2025-10-12 18:36:06,447 - INFO - Usando dispositivo: cuda
/home/exx/users/nicolas/venv/lib/python3.10/site-packages/torch/autograd/graph.py:829: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:179.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/home/exx/users/nicolas/TCC/BurgersEquation/2_Train.py", line 124, in <module>
    loss_log.append([loss.item(), loss_dados.item(), loss_EDP.item(), loss_ci.item()])
NameError: name 'loss_EDP' is not defined. Did you mean: 'loss_log'?
